server:
  port: 8004
spring:
  application:
    name:  cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_manager?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: morven
    password:  19920923Wei.
  cloud:
    zookeeper:
      connect-string: 192.168.113.129:2181